// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_b1_a7zVpM5ai2yBYzs1YZse0M-3JVVM',
    appId: '1:487580925807:web:15e9ec143e9c962608329a',
    messagingSenderId: '487580925807',
    projectId: 'instagram-clone-d04d4',
    authDomain: 'instagram-clone-d04d4.firebaseapp.com',
    storageBucket: 'instagram-clone-d04d4.appspot.com',
    measurementId: 'G-WJ779RSK9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiKqaEywFc7Nbz2XK-jtVC7kiNF-kXgv4',
    appId: '1:487580925807:android:4ace427be680f46808329a',
    messagingSenderId: '487580925807',
    projectId: 'instagram-clone-d04d4',
    storageBucket: 'instagram-clone-d04d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWY4G1eKqB0x5kjfg_kXAlwLPVs_FyYfQ',
    appId: '1:487580925807:ios:802c909d095f86a308329a',
    messagingSenderId: '487580925807',
    projectId: 'instagram-clone-d04d4',
    storageBucket: 'instagram-clone-d04d4.appspot.com',
    iosClientId: '487580925807-irstv2s7lbhtved8fk9gf1ecq3vv3h0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWY4G1eKqB0x5kjfg_kXAlwLPVs_FyYfQ',
    appId: '1:487580925807:ios:802c909d095f86a308329a',
    messagingSenderId: '487580925807',
    projectId: 'instagram-clone-d04d4',
    storageBucket: 'instagram-clone-d04d4.appspot.com',
    iosClientId: '487580925807-irstv2s7lbhtved8fk9gf1ecq3vv3h0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodDemo',
  );
}
